# Generated by Django 3.2.4 on 2021-06-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sumary',
            new_name='summary',
        ),
    ]
