# Generated by Django 3.2.4 on 2021-06-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0003_auto_20210622_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
